/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ASUS
 */
public class FChucNang extends javax.swing.JFrame {

    /**
     * Creates new form FChucNang
     */
    public FChucNang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQLGV_HHPBUV = new javax.swing.JButton();
        btnTTGV = new javax.swing.JButton();
        btnQLDT = new javax.swing.JButton();
        btnQLSV_DT = new javax.swing.JButton();
        btnQLDT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("VNI 27 Bendigo", 3, 14)); // NOI18N
        jLabel1.setText("CHÀO MỪNG ĐẾN VỚI CHƯƠNG TRÌNH QUẢN LÝ ĐỒ ÁN TỐT NGHIỆP");

        btnQLGV_HHPBUV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/presentation-glyph-black-icon-png_309003.jpg"))); // NOI18N
        btnQLGV_HHPBUV.setText("QUẢN LÝ GIÁO VIÊN PHỤ TRÁCH HD- PB- UV");
        btnQLGV_HHPBUV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLGV_HHPBUVMouseClicked(evt);
            }
        });

        btnTTGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img_534312.png"))); // NOI18N
        btnTTGV.setText("QUẢN LÝ THÔNG TIN GIẢNG  VIÊN  ");
        btnTTGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTTGVMouseClicked(evt);
            }
        });

        btnQLDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images.jpg"))); // NOI18N
        btnQLDT.setText("QUẢN LÝ HỘI ĐỒNG");
        btnQLDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLDTMouseClicked(evt);
            }
        });

        btnQLSV_DT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kissclipart-diploma-icon-clipart-diploma-academic-degree-compu-169b92d5d13a22cb.jpg"))); // NOI18N
        btnQLSV_DT.setText("QUẢN LÝ SINH VIÊN & ĐỀ TÀI THỰC HIỆN");
        btnQLSV_DT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLSV_DTMouseClicked(evt);
            }
        });
        btnQLSV_DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSV_DTActionPerformed(evt);
            }
        });

        btnQLDT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tải xuống.jpg"))); // NOI18N
        btnQLDT1.setText("QUẢN LÝ ĐỀ TÀI");
        btnQLDT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLDT1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQLDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnQLSV_DT, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnQLGV_HHPBUV, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTTGV, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnQLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnQLSV_DT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnQLGV_HHPBUV, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnTTGV, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnQLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnQLDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSV_DTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSV_DTMouseClicked
        
         FQLSV_DT f = new FQLSV_DT();
                    f.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_btnQLSV_DTMouseClicked

    private void btnQLSV_DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSV_DTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLSV_DTActionPerformed

    private void btnQLGV_HHPBUVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLGV_HHPBUVMouseClicked
        
         FGV_HD_PB f = new FGV_HD_PB();
                    f.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_btnQLGV_HHPBUVMouseClicked

    private void btnTTGVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTTGVMouseClicked
        
         FGV_HH_HV f = new FGV_HH_HV();
                    f.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_btnTTGVMouseClicked

    private void btnQLDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDTMouseClicked
        
         FDeTaiDoAn f = new FDeTaiDoAn();
                    f.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_btnQLDTMouseClicked

    private void btnQLDT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDT1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLDT1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FChucNang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLDT;
    private javax.swing.JButton btnQLDT1;
    private javax.swing.JButton btnQLGV_HHPBUV;
    private javax.swing.JButton btnQLSV_DT;
    private javax.swing.JButton btnTTGV;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
